# nixpacks.toml
[phases.setup]
aptPkgs = [
  "libgobject-2.0-0",
  "libcairo2",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libpangoft2-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libharfbuzz0b",
  "libharfbuzz-subset0",
  "libfontconfig1",
  "libfreetype6",
  "libjpeg-turbo8",
  "libpng16-16",
  "libffi-dev",
  "fonts-dejavu-core",
]
